//Stocks
export const GET_SINGLE_STOCK_DAY = 'GET_SINGLE_STOCK_DAY';
export const SET_STOCK_META_DATA = 'SET_STOCK_META_DATA';
export const STOCK_META_DATA_LOAD = 'STOCK_META_DATA_LOAD';
export const SET_DAILY_DATA = 'SET_DAILY_DATA';
export const STOCK_DAILY_LOAD = 'STOCK_DAILY_LOAD';
//Exchanges
export const GET_NASDAQ_EXCHANGE_LIST = 'GET_NASDAQ_EXCHANGE_LIST';
export const ADD_NASDAQ_EXCHANGE_LIST = 'ADD_NASDAQ_EXCHANGE_LIST';
export const EXCHANGE_LIST_LOAD = 'EXCHANGE_LIST_LOAD';
export const SET_SELECTED_STOCKS = 'SET_SELECTED_STOCKS';
//News
export const NEWS_HEADLINE_FROM_KW_LOAD = 'NEWS_HEADLINE_FROM_KW_LOAD';
export const SET_HEADLINE_FROM_KW = 'SET_HEADLINE_FROM_KW';
